---
# FNX Production Account - Production Environment Stack
# Primary production environment with full security and compliance
# Stack: fnx-prod-us-west-2-production

# Stack imports (order matters - globals first, then mixins, then catalogs)
imports:
  # Global settings
  - "_globals/globals"

  # Mixins (account -> region -> environment -> compliance)
  - "mixins/accounts/production"
  - "mixins/regions/us-west-2"
  - "mixins/environments/production"
  - "mixins/compliance/soc2"
  - "mixins/compliance/iso27001"

  # Component catalogs
  - "catalogs/foundation/vpc"
  - "catalogs/platform/eks"

# Stack metadata
metadata:
  stack_name: "fnx-prod-us-west-2-production"
  description: "FNX production environment in US West 2 with full compliance"
  environment_type: "production"
  deployment_order: 4  # Final production deployment
  compliance_frameworks: ["soc2", "iso27001"]

# Stack-level variables
vars:
  # Stack identification
  tenant: "fnx"
  account: "prod"
  region: "us-west-2"
  environment: "production"

  # Naming
  name_prefix: "${tenant}-${environment}"

  # Network configuration (production CIDR range)
  vpc_cidr: "192.168.0.0/16"       # Production network range
  availability_zones: ["us-west-2a", "us-west-2b", "us-west-2c"]

  # Subnet allocation (larger subnets for production workloads)
  private_subnets: ["192.168.1.0/22", "192.168.5.0/22", "192.168.9.0/22"]    # 1024 IPs each
  public_subnets: ["192.168.101.0/24", "192.168.102.0/24", "192.168.103.0/24"] # 256 IPs each
  database_subnets: ["192.168.201.0/24", "192.168.202.0/24", "192.168.203.0/24"] # 256 IPs each
  elasticache_subnets: ["192.168.251.0/24", "192.168.252.0/24", "192.168.253.0/24"] # 256 IPs each

  # DNS configuration
  domain_name: "fnx.platform.company.com"

  # Cost management (production)
  cost_center: "Production Operations"
  project_name: "FNX Platform"
  resource_owner: "platform-ops@company.com"

  # Production-specific configuration
  high_availability_enabled: true
  disaster_recovery_enabled: true
  cross_region_backup_enabled: true

  # Compliance configuration
  compliance_frameworks: ["soc2", "iso27001"]
  audit_logging_enabled: true
  security_monitoring_enabled: true

# Component configurations
components:
  terraform:
    # VPC component (production configuration)
    vpc:
      vars:
        # Network configuration
        cidr_block: "${vpc_cidr}"
        azs: "${availability_zones}"
        private_subnets: "${private_subnets}"
        public_subnets: "${public_subnets}"
        database_subnets: "${database_subnets}"
        elasticache_subnets: "${elasticache_subnets}"

        # Production VPC settings
        enable_nat_gateway: true
        single_nat_gateway: false         # Multi-AZ NAT gateways for HA
        enable_vpn_gateway: false
        enable_dns_hostnames: true
        enable_dns_support: true

        # Enhanced security settings
        enable_flow_log: true
        flow_log_destination_type: "cloud-watch-logs"
        flow_log_log_format: "${version} ${account-id} ${interface-id} ${srcaddr} ${dstaddr} ${srcport} ${dstport} ${protocol} ${packets} ${bytes} ${windowstart} ${windowend} ${action} ${flowlogstatus}"

        # Network ACLs for additional security
        manage_default_network_acl: true
        default_network_acl_name: "${name_prefix}-default-nacl"
        public_dedicated_network_acl: true
        private_dedicated_network_acl: true
        database_dedicated_network_acl: true

        # Security group management
        manage_default_security_group: true
        default_security_group_name: "${name_prefix}-default-sg"

      tags:
        Name: "${name_prefix}-vpc"
        BusinessCritical: "true"
        HighAvailability: "true"
        ComplianceScope: "soc2,iso27001"
        SecurityLevel: "High"

    # EKS component (production configuration)
    eks:
      vars:
        # Cluster configuration
        cluster_name: "${name_prefix}-eks"
        cluster_version: "1.28"

        # Network configuration
        vpc_id: "${components.terraform.vpc.vpc_id}"
        subnet_ids: "${components.terraform.vpc.private_subnets}"

        # Production security settings
        cluster_endpoint_private_access: true
        cluster_endpoint_public_access: false  # Private cluster for production
        cluster_endpoint_public_access_cidrs: []

        # Cluster encryption
        cluster_encryption_config:
          - provider_key_arn: "${module.kms.key_arn}"
            resources: ["secrets"]

        # Production add-ons with specific versions
        cluster_addons:
          coredns:
            addon_version: "v1.10.1-eksbuild.5"
            resolve_conflicts: "OVERWRITE"
          kube-proxy:
            addon_version: "v1.28.2-eksbuild.2"
            resolve_conflicts: "OVERWRITE"
          vpc-cni:
            addon_version: "v1.15.1-eksbuild.1"
            resolve_conflicts: "OVERWRITE"
            configuration_values: |
              {
                "env": {
                  "ENABLE_PREFIX_DELEGATION": "true",
                  "ENABLE_POD_ENI": "true",
                  "ENABLE_NETWORK_POLICY": "true"
                }
              }
          aws-ebs-csi-driver:
            addon_version: "v1.25.0-eksbuild.1"
            resolve_conflicts: "OVERWRITE"

        # Production node groups
        eks_managed_node_groups:
          production_main:
            instance_types: ["m5.large", "m5.xlarge"]
            capacity_type: "ON_DEMAND"      # Reliability over cost
            min_size: 3                     # Minimum for HA
            max_size: 20
            desired_size: 6                 # Start with higher capacity

            # Production-specific configuration
            ami_type: "AL2_x86_64"
            disk_size: 50                   # Larger disk for production workloads

            # Labels and taints
            labels:
              node-type: "production-main"
              environment: "production"
              business-critical: "true"
              compliance: "soc2-iso27001"

            taints:
              - key: "production"
                value: "true"
                effect: "NO_SCHEDULE"

            # Update configuration (conservative)
            update_config:
              max_unavailable: 1            # Conservative update strategy

            # Launch template configuration
            create_launch_template: true
            launch_template_name: "${name_prefix}-production-main"
            launch_template_description: "Production main node group"

            # Enhanced security
            metadata_options:
              http_endpoint: "enabled"
              http_tokens: "required"       # IMDSv2 required
              http_put_response_hop_limit: 2

          production_spot:
            # Secondary node group with spot instances for non-critical workloads
            instance_types: ["m5.large", "m5.xlarge", "c5.large", "c5.xlarge"]
            capacity_type: "SPOT"
            min_size: 0
            max_size: 10
            desired_size: 2

            labels:
              node-type: "production-spot"
              environment: "production"
              capacity-type: "spot"

            taints:
              - key: "spot-instance"
                value: "true"
                effect: "NO_SCHEDULE"

        # Comprehensive logging for compliance
        cluster_enabled_log_types: ["api", "audit", "authenticator", "controllerManager", "scheduler"]
        cloudwatch_log_group_retention_in_days: 2555  # 7 years for compliance

        # Additional security groups
        cluster_security_group_additional_rules:
          ingress_nodes_443:
            description: "Node groups to cluster API"
            protocol: "tcp"
            from_port: 443
            to_port: 443
            type: "ingress"
            source_node_security_group: true

        # OIDC provider for service account authentication
        enable_irsa: true

      tags:
        Name: "${name_prefix}-eks"
        BusinessCritical: "true"
        HighAvailability: "true"
        KubernetesVersion: "1.28"
        ClusterAccess: "private"
        ComplianceScope: "soc2,iso27001"
        SecurityLevel: "High"

# Stack-level tags (applied to all resources)
tags:
  # Stack identification
  Stack: "fnx-prod-us-west-2-production"
  Tenant: "fnx"
  Account: "prod"
  Region: "us-west-2"
  Environment: "production"

  # Environment characteristics
  EnvironmentType: "production"
  BusinessCritical: "true"
  HighAvailability: "true"
  DisasterRecovery: "true"
  CrossRegionBackup: "true"

  # Security and compliance
  SecurityLevel: "High"
  ComplianceRequired: "true"
  ComplianceFrameworks: "SOC2,ISO27001"
  AuditScope: "true"
  EncryptionRequired: "true"

  # Operational tags
  BackupRequired: "true"
  BackupRetention: "30days"
  MonitoringLevel: "Enhanced"
  AlertingEnabled: "true"

  # Cost and management
  CostCenter: "Production Operations"
  Project: "FNX Platform"
  Owner: "platform-ops@company.com"
  ManagedBy: "Terraform"
  CreatedBy: "Atmos"

  # Service level
  ServiceLevel: "Production"
  SLA: "99.95%"
  RTO: "1hour"
  RPO: "15minutes"

  # Data classification
  DataClassification: "Internal"
  DataSensitivity: "Medium"