---
# Serverless API Stack Template
# Production-ready serverless REST API infrastructure
# Version: 1.0.0

name: serverless-api-stack
description: "Serverless API infrastructure with Lambda, API Gateway, and DynamoDB"
version: "1.0.0"
maturity: "production"

template:
  category: "patterns/serverless-apps"
  use_cases:
    - "REST APIs"
    - "GraphQL APIs"
    - "Webhook handlers"
    - "Backend for mobile/web apps"
    - "Event-driven microservices"

  architecture:
    components:
      - name: "API Layer"
        components: ["api-gateway", "cognito"]
        description: "API management and authentication"
      - name: "Compute Layer"
        components: ["lambda"]
        description: "Serverless function execution"
      - name: "Data Layer"
        components: ["dynamodb", "s3"]
        description: "NoSQL database and object storage"
      - name: "Event Processing"
        components: ["sqs", "sns", "eventbridge"]
        description: "Asynchronous event handling"

  estimated_cost:
    minimum: "$10/month"
    typical: "$100/month"
    maximum: "$1000+/month"
    note: "Highly variable based on request volume"

  deployment_time: "15-25 minutes"

# Stack configuration
import:
  - catalog/_base/defaults
  - catalog/iam/defaults
  - catalog/monitoring/defaults

components:
  terraform:
    # ===========================================
    # API LAYER
    # ===========================================
    apigateway:
      component: "apigateway"
      vars:
        enabled: true
        api_name: "${tenant}-${environment}-serverless-api"
        description: "Serverless REST API for ${environment}"
        api_type: "REST"
        endpoint_type: ["REGIONAL"]

        # Authorization
        authorizer_type: "COGNITO_USER_POOLS"
        cognito_user_pool_arns: ["${output.cognito.user_pool_arn}"]

        # CORS
        enable_cors: true
        cors_allow_origins: ["*"]
        cors_allow_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
        cors_allow_headers: ["Content-Type", "Authorization", "X-Amz-Date", "X-Api-Key"]

        # Logging
        enable_logging: true
        log_format: '{ "requestId":"$context.requestId", "ip":"$context.identity.sourceIp", "requestTime":"$context.requestTime", "httpMethod":"$context.httpMethod", "resourcePath":"$context.resourcePath", "status":"$context.status", "responseLatency":"$context.responseLatency" }'
        log_retention_days: 30

        # Throttling
        stage_name: "${environment}"
        throttling_burst_limit: 1000
        throttling_rate_limit: 500

        # API Keys
        create_api_key: true
        create_usage_plan: true
        usage_plan_name: "${tenant}-${environment}-standard"
        usage_plan_quota_limit: 100000
        usage_plan_quota_period: "MONTH"
        usage_plan_throttle_burst_limit: 500
        usage_plan_throttle_rate_limit: 100

        # Custom domain (optional)
        create_custom_domain: false
        # domain_name: "api.${domain}"
        # certificate_arn: "${output.acm.certificate_arn}"

      tags:
        StackType: "serverless-api"
        Layer: "api"

    # ===========================================
    # AUTHENTICATION
    # ===========================================
    cognito:
      component: "cognito"
      vars:
        enabled: true
        user_pool_name: "${tenant}-${environment}-users"

        # Password policy
        password_policy:
          minimum_length: 12
          require_lowercase: true
          require_uppercase: true
          require_numbers: true
          require_symbols: true
          temporary_password_validity_days: 7

        # MFA
        mfa_configuration: "OPTIONAL"
        software_token_mfa_enabled: true

        # Account recovery
        account_recovery_setting:
          - name: "verified_email"
            priority: 1
          - name: "verified_phone_number"
            priority: 2

        # Email configuration
        email_verification_subject: "Verify your email for ${tenant}"
        email_verification_message: "Your verification code is {####}"

        # Schema
        schema:
          - name: "email"
            attribute_data_type: "String"
            required: true
            mutable: true
          - name: "name"
            attribute_data_type: "String"
            required: true
            mutable: true

        # App client
        app_clients:
          - name: "${tenant}-${environment}-web-client"
            generate_secret: false
            allowed_oauth_flows: ["code", "implicit"]
            allowed_oauth_scopes: ["email", "openid", "profile"]
            callback_urls: ["https://app.${domain}/callback"]
            logout_urls: ["https://app.${domain}/logout"]
            supported_identity_providers: ["COGNITO"]

      tags:
        StackType: "serverless-api"
        Layer: "auth"

    # ===========================================
    # COMPUTE LAYER
    # ===========================================
    lambda-api:
      component: "lambda"
      depends_on:
        - iam
      vars:
        enabled: true

        functions:
          # CRUD API handlers
          api-handler:
            function_name: "${tenant}-${environment}-api-handler"
            description: "Main API request handler"
            runtime: "python3.11"
            handler: "handler.lambda_handler"
            memory_size: 512
            timeout: 30
            architecture: "arm64"

            # Environment variables
            environment_variables:
              ENVIRONMENT: "${environment}"
              TABLE_NAME: "${output.dynamodb.table_name}"
              LOG_LEVEL: "INFO"

            # VPC (optional for database access)
            vpc_config:
              enabled: false

            # Tracing
            tracing_config:
              mode: "Active"

            # Provisioned concurrency (production)
            provisioned_concurrency: 0

          # Async processor
          async-processor:
            function_name: "${tenant}-${environment}-async-processor"
            description: "Asynchronous event processor"
            runtime: "python3.11"
            handler: "processor.lambda_handler"
            memory_size: 256
            timeout: 300
            architecture: "arm64"

            environment_variables:
              ENVIRONMENT: "${environment}"
              TABLE_NAME: "${output.dynamodb.table_name}"

            # SQS trigger
            event_source_mapping:
              sqs:
                event_source_arn: "${output.sqs.queue_arn}"
                batch_size: 10
                maximum_batching_window_in_seconds: 5

          # Scheduled tasks
          scheduler:
            function_name: "${tenant}-${environment}-scheduler"
            description: "Scheduled task runner"
            runtime: "python3.11"
            handler: "scheduler.lambda_handler"
            memory_size: 256
            timeout: 300
            architecture: "arm64"

            environment_variables:
              ENVIRONMENT: "${environment}"

            # CloudWatch Events schedule
            schedule_expression: "rate(1 hour)"

        # Common settings
        common_environment_variables:
          POWERTOOLS_SERVICE_NAME: "${tenant}-api"
          POWERTOOLS_METRICS_NAMESPACE: "${tenant}-${environment}"

        # Layers
        layers:
          - powertools

      tags:
        StackType: "serverless-api"
        Layer: "compute"

    # ===========================================
    # DATA LAYER
    # ===========================================
    dynamodb:
      component: "dynamodb"
      vars:
        enabled: true
        table_name: "${tenant}-${environment}-data"
        billing_mode: "PAY_PER_REQUEST"

        # Primary key
        hash_key: "pk"
        range_key: "sk"

        # Attributes
        attributes:
          - name: "pk"
            type: "S"
          - name: "sk"
            type: "S"
          - name: "gsi1pk"
            type: "S"
          - name: "gsi1sk"
            type: "S"
          - name: "gsi2pk"
            type: "S"

        # Global Secondary Indexes
        global_secondary_indexes:
          - name: "gsi1"
            hash_key: "gsi1pk"
            range_key: "gsi1sk"
            projection_type: "ALL"
          - name: "gsi2"
            hash_key: "gsi2pk"
            projection_type: "KEYS_ONLY"

        # TTL
        ttl_enabled: true
        ttl_attribute_name: "ttl"

        # Point-in-time recovery
        point_in_time_recovery_enabled: true

        # Encryption
        server_side_encryption_enabled: true
        server_side_encryption_kms_key_arn: null  # Use AWS managed key

        # Streams
        stream_enabled: true
        stream_view_type: "NEW_AND_OLD_IMAGES"

      tags:
        StackType: "serverless-api"
        Layer: "data"

    s3-storage:
      component: "s3"
      vars:
        enabled: true
        bucket_name: "${tenant}-${environment}-storage"

        # Versioning
        versioning_enabled: true

        # Encryption
        sse_algorithm: "aws:kms"

        # Lifecycle rules
        lifecycle_rules:
          - id: "archive-old-objects"
            enabled: true
            transitions:
              - days: 90
                storage_class: "STANDARD_IA"
              - days: 365
                storage_class: "GLACIER"
            expiration:
              days: 730

        # CORS for direct uploads
        cors_rules:
          - allowed_headers: ["*"]
            allowed_methods: ["GET", "PUT", "POST"]
            allowed_origins: ["*"]
            max_age_seconds: 3600

        # Block public access
        block_public_access: true

      tags:
        StackType: "serverless-api"
        Layer: "data"

    # ===========================================
    # EVENT PROCESSING
    # ===========================================
    sqs:
      component: "sqs"
      vars:
        enabled: true
        queue_name: "${tenant}-${environment}-events"

        # Visibility timeout (should be >= Lambda timeout)
        visibility_timeout_seconds: 300

        # Message retention
        message_retention_seconds: 1209600  # 14 days

        # Dead letter queue
        create_dlq: true
        dlq_name: "${tenant}-${environment}-events-dlq"
        max_receive_count: 3

        # Encryption
        kms_master_key_id: "alias/aws/sqs"
        sqs_managed_sse_enabled: false

      tags:
        StackType: "serverless-api"
        Layer: "messaging"

    sns:
      component: "sns"
      vars:
        enabled: true
        topic_name: "${tenant}-${environment}-notifications"

        # Encryption
        kms_master_key_id: "alias/aws/sns"

        # Subscriptions
        subscriptions:
          - protocol: "sqs"
            endpoint: "${output.sqs.queue_arn}"
            filter_policy:
              event_type:
                - "notification"

      tags:
        StackType: "serverless-api"
        Layer: "messaging"

    # ===========================================
    # IAM
    # ===========================================
    iam:
      component: "iam"
      vars:
        enabled: true

        # Lambda execution role
        lambda_execution_role:
          name: "${tenant}-${environment}-lambda-role"
          assume_role_policy:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Principal:
                  Service: "lambda.amazonaws.com"
                Action: "sts:AssumeRole"

          policies:
            dynamodb:
              - Effect: "Allow"
                Action:
                  - "dynamodb:GetItem"
                  - "dynamodb:PutItem"
                  - "dynamodb:UpdateItem"
                  - "dynamodb:DeleteItem"
                  - "dynamodb:Query"
                  - "dynamodb:Scan"
                  - "dynamodb:BatchGetItem"
                  - "dynamodb:BatchWriteItem"
                Resource:
                  - "${output.dynamodb.table_arn}"
                  - "${output.dynamodb.table_arn}/index/*"

            s3:
              - Effect: "Allow"
                Action:
                  - "s3:GetObject"
                  - "s3:PutObject"
                  - "s3:DeleteObject"
                  - "s3:ListBucket"
                Resource:
                  - "${output.s3-storage.bucket_arn}"
                  - "${output.s3-storage.bucket_arn}/*"

            sqs:
              - Effect: "Allow"
                Action:
                  - "sqs:SendMessage"
                  - "sqs:ReceiveMessage"
                  - "sqs:DeleteMessage"
                  - "sqs:GetQueueAttributes"
                Resource:
                  - "${output.sqs.queue_arn}"

            logs:
              - Effect: "Allow"
                Action:
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                Resource: "arn:aws:logs:*:*:*"

            xray:
              - Effect: "Allow"
                Action:
                  - "xray:PutTraceSegments"
                  - "xray:PutTelemetryRecords"
                Resource: "*"

      tags:
        StackType: "serverless-api"
        Layer: "security"

    # ===========================================
    # OBSERVABILITY
    # ===========================================
    monitoring:
      component: "monitoring"
      depends_on:
        - lambda-api
        - apigateway
        - dynamodb
      vars:
        enabled: true

        # Dashboard
        create_dashboard: true
        dashboard_name: "${tenant}-${environment}-serverless-api"

        # Dashboard widgets
        dashboard_widgets:
          - type: "metric"
            title: "API Gateway Requests"
            metrics:
              - namespace: "AWS/ApiGateway"
                metric_name: "Count"
                dimensions:
                  ApiName: "${output.apigateway.api_name}"
          - type: "metric"
            title: "Lambda Invocations"
            metrics:
              - namespace: "AWS/Lambda"
                metric_name: "Invocations"
          - type: "metric"
            title: "Lambda Errors"
            metrics:
              - namespace: "AWS/Lambda"
                metric_name: "Errors"
          - type: "metric"
            title: "DynamoDB Consumed Capacity"
            metrics:
              - namespace: "AWS/DynamoDB"
                metric_name: "ConsumedReadCapacityUnits"
              - namespace: "AWS/DynamoDB"
                metric_name: "ConsumedWriteCapacityUnits"

        # Alarms
        alarm_notifications_enabled: true
        sns_topic_name: "${tenant}-${environment}-serverless-alarms"

        alarms:
          api-5xx-errors:
            metric_name: "5XXError"
            namespace: "AWS/ApiGateway"
            statistic: "Sum"
            period: 60
            evaluation_periods: 3
            threshold: 10
            comparison_operator: "GreaterThanThreshold"
            dimensions:
              ApiName: "${output.apigateway.api_name}"

          lambda-errors:
            metric_name: "Errors"
            namespace: "AWS/Lambda"
            statistic: "Sum"
            period: 60
            evaluation_periods: 3
            threshold: 5
            comparison_operator: "GreaterThanThreshold"

          lambda-duration:
            metric_name: "Duration"
            namespace: "AWS/Lambda"
            statistic: "p99"
            period: 300
            evaluation_periods: 3
            threshold: 5000  # 5 seconds
            comparison_operator: "GreaterThanThreshold"

          dynamodb-throttling:
            metric_name: "ThrottledRequests"
            namespace: "AWS/DynamoDB"
            statistic: "Sum"
            period: 60
            evaluation_periods: 3
            threshold: 5
            comparison_operator: "GreaterThanThreshold"

          sqs-dlq-messages:
            metric_name: "ApproximateNumberOfMessagesVisible"
            namespace: "AWS/SQS"
            statistic: "Sum"
            period: 300
            evaluation_periods: 1
            threshold: 1
            comparison_operator: "GreaterThanThreshold"
            dimensions:
              QueueName: "${output.sqs.dlq_name}"

      tags:
        StackType: "serverless-api"
        Layer: "observability"

# Deployment order
deployment_order:
  - stage: 1
    components: [iam]
    parallel: false
  - stage: 2
    components: [dynamodb, s3-storage, sqs, sns, cognito]
    parallel: true
  - stage: 3
    components: [lambda-api]
    parallel: false
  - stage: 4
    components: [apigateway]
    parallel: false
  - stage: 5
    components: [monitoring]
    parallel: false

# Validation rules
validation:
  pre_deployment:
    - check: "lambda_code_exists"
      description: "Verify Lambda deployment packages exist"
    - check: "iam_permissions"
      description: "Verify IAM permissions for deployment"
  post_deployment:
    - check: "api_gateway_accessible"
      description: "Verify API Gateway responds to health check"
    - check: "lambda_invokable"
      description: "Verify Lambda functions can be invoked"
    - check: "dynamodb_accessible"
      description: "Verify DynamoDB table is accessible"
