apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: default
spec:
  # References a JSON-encoded data object with the mapping of zone name to the internal AWS zone ID (AZ ID)
  # This is used to avoid hard-coding AZ IDs as they can differ across AWS accounts.
  template:
    spec:
      requirements:
        - key: "karpenter.k8s.aws/instance-category"
          operator: In
          values: ["c", "m", "r", "t"]
        - key: "karpenter.k8s.aws/instance-generation"
          operator: Gt
          values: ["4"]
        - key: "kubernetes.io/arch"
          operator: In
          values: ["amd64"]
        - key: "karpenter.sh/capacity-type"
          operator: In
          values: ["on-demand"]
      nodeClassRef:
        name: default
  limits:
    cpu: 1000
    memory: 1000Gi
  disruption:
    consolidationPolicy: WhenEmpty
    consolidateAfter: 30s

---

apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: default
spec:
  amiFamily: AL2
  role: karpenter-node-role
  securityGroupSelector:
    Name: "testenv-01-main-node-sg"
  subnetSelector:
    Name: "testenv-01-private-*"
  tags:
    Environment: testenv-01
    ManagedBy: karpenter
  userData: |
    #!/bin/bash
    set -o xtrace
    /etc/eks/bootstrap.sh testenv-01-main