---
{{- if .Values.backstage.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "idp-platform.fullname" . }}-backstage
  labels:
    {{- include "idp-platform.labels" . | nindent 4 }}
    app.kubernetes.io/component: backstage
spec:
  {{- if not .Values.backstage.autoscaling.enabled }}
  replicas: {{ .Values.backstage.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "idp-platform.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: backstage
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/backstage-configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/backstage-secret.yaml") . | sha256sum }}
        prometheus.io/scrape: "true"
        prometheus.io/port: "7007"
        prometheus.io/path: "/api/app/metrics"
      labels:
        {{- include "idp-platform.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: backstage
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "idp-platform.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: backstage
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.backstage.image.repository }}:{{ .Values.backstage.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.backstage.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 7007
              protocol: TCP
          env:
            - name: NODE_ENV
              value: "production"
            - name: BACKSTAGE_APP_CONFIG
              value: "/app/config/app-config.yaml,/app/config/app-config.production.yaml"
            {{- range .Values.backstage.env }}
            - name: {{ .name }}
              {{- if .value }}
              value: {{ .value | quote }}
              {{- else if .valueFrom }}
              valueFrom:
                {{- toYaml .valueFrom | nindent 16 }}
              {{- end }}
            {{- end }}
          volumeMounts:
            - name: app-config
              mountPath: /app/config
              readOnly: true
            - name: auth-config
              mountPath: /app/auth-config
              readOnly: true
            - name: tmp
              mountPath: /tmp
          livenessProbe:
            {{- toYaml .Values.backstage.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.backstage.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.backstage.resources | nindent 12 }}
      volumes:
        - name: app-config
          configMap:
            name: {{ include "idp-platform.fullname" . }}-backstage-config
        - name: auth-config
          secret:
            secretName: {{ include "idp-platform.fullname" . }}-backstage-auth
        - name: tmp
          emptyDir: {}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}