---
{{- if and .Values.backstage.enabled .Values.backstage.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "idp-platform.fullname" . }}-backstage
  labels:
    {{- include "idp-platform.labels" . | nindent 4 }}
    app.kubernetes.io/component: backstage
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "idp-platform.fullname" . }}-backstage
  minReplicas: {{ .Values.backstage.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.backstage.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.backstage.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.backstage.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.backstage.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.backstage.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 300
      policies:
        - type: Percent
          value: 100
          periodSeconds: 60
        - type: Pods
          value: 2
          periodSeconds: 60
      selectPolicy: Max
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
        - type: Percent
          value: 50
          periodSeconds: 60
        - type: Pods
          value: 1
          periodSeconds: 60
      selectPolicy: Min
---
{{- end }}
{{- if and .Values.platformApi.enabled .Values.platformApi.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "idp-platform.fullname" . }}-platform-api
  labels:
    {{- include "idp-platform.labels" . | nindent 4 }}
    app.kubernetes.io/component: platform-api
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "idp-platform.fullname" . }}-platform-api
  minReplicas: {{ .Values.platformApi.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.platformApi.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.platformApi.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.platformApi.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.platformApi.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.platformApi.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 180
      policies:
        - type: Percent
          value: 100
          periodSeconds: 30
        - type: Pods
          value: 4
          periodSeconds: 30
      selectPolicy: Max
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
        - type: Percent
          value: 50
          periodSeconds: 60
        - type: Pods
          value: 2
          periodSeconds: 60
      selectPolicy: Min
{{- end }}