name: apply-environment
description: "Apply changes for all components in an environment"

workflows:
  apply:
    steps:
    - run:
        command: |
          # Use Python-based CLI to apply all components
          gaia workflow apply-environment \
            --tenant ${tenant} \
            --account ${account} \
            --environment ${environment} \
            --auto-approve ${auto_approve:-false} \
            --parallel ${parallel:-false}
            
          # Perform validation checks if successful
          if [ $? -eq 0 ]; then
            echo "Deployment completed successfully."
            
            # Validate deployment
            echo "Running validation checks..."
            gaia workflow validate \
              --tenant ${tenant} \
              --account ${account} \
              --environment ${environment}
          else
            echo "Deployment failed."
            exit 1
          fi
        env:
          AWS_SDK_LOAD_CONFIG: 1