---
name: create-environment-template
description: "Create a new environment using Copier templates"

workflows:
  create:
    steps:
    - run:
        command: |
          # Execute external script with environment variables
          TENANT="${tenant}" \
          ACCOUNT="${account}" \
          ENVIRONMENT="${environment}" \
          VPC_CIDR="${vpc_cidr}" \
          ENV_TYPE="${env_type}" \
          REGION="${region}" \
          EKS_ENABLED="${eks}" \
          RDS_ENABLED="${rds}" \
          TEAM_EMAIL="${team_email}" \
          FORCE_OVERWRITE="${force_overwrite:-false}" \
          AUTO_VALIDATE="${auto_validate:-false}" \
          AUTO_DEPLOY="${auto_deploy:-false}" \
          ${ATMOS_COMPONENT_PATH:-$(git rev-parse --show-toplevel)}/scripts/workflows/create-environment-template.sh
        env:
          AWS_SDK_LOAD_CONFIG: 1
