name: destroy-environment
description: "Destroy all components in an environment"

workflows:
  destroy:
    steps:
    - run:
        command: |
          # Use Python-based CLI for safer and more reliable destroy operations
          gaia workflow destroy-environment \
            --tenant ${tenant} \
            --account ${account} \
            --environment ${environment} \
            --auto-approve ${auto_approve:-false} \
            --safe-destroy ${safe_destroy:-true}
            
          EXIT_CODE=$?
          
          if [ $EXIT_CODE -eq 0 ]; then
            echo "Environment destruction completed successfully."
          else
            echo "Environment destruction failed or was partially completed."
            echo "Review logs for details on any remaining resources."
            exit $EXIT_CODE
          fi
        env:
          AWS_SDK_LOAD_CONFIG: 1