name: onboard-environment
description: "Onboard a new environment with infrastructure"

workflows:
  onboard:
    steps:
    - run:
        command: |
          # First create the environment template
          TENANT="${tenant}" \
          ACCOUNT="${account}" \
          ENVIRONMENT="${environment}" \
          VPC_CIDR="${vpc_cidr}" \
          REGION="${region:-}" \
          ENV_TYPE="${env_type:-}" \
          gaia template create-environment \
            --tenant ${tenant} \
            --account ${account} \
            --environment ${environment} \
            --vpc-cidr ${vpc_cidr} \
            ${region:+--region ${region}} \
            ${env_type:+--env-type ${env_type}}
          
          if [ $? -ne 0 ]; then
            echo "Failed to create environment template."
            exit 1
          fi
          
          # Deploy the environment if auto-deploy is enabled
          if [ "${auto_deploy:-false}" == "true" ]; then
            echo "Auto-deploying environment..."
            
            gaia workflow apply-environment \
              --tenant ${tenant} \
              --account ${account} \
              --environment ${environment} \
              --auto-approve true
            
            if [ $? -ne 0 ]; then
              echo "Environment deployment failed."
              exit 1
            fi
            
            echo "Environment successfully onboarded and deployed!"
          else
            echo "Environment template created. Run 'gaia workflow apply-environment' to deploy."
          fi
        env:
          AWS_SDK_LOAD_CONFIG: 1
          MANAGEMENT_ACCOUNT_ID: ${management_account_id}
          ALARM_EMAIL: ${alarm_email}