name: plan-environment
description: "Plan changes for all components in an environment with automatic discovery"

workflows:
  plan:
    steps:
    - run:
        command: |
          # Get CLI version automatically (in a cross-platform way)
          ATMOS_CLI_VERSION=$(atmos version | sed -n 's/.*Atmos \([0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*\).*/\1/p')
          echo "Using Atmos CLI version: ${ATMOS_CLI_VERSION}"
          
          # Validate required variables
          if [ -z "${tenant}" ] || [ -z "${account}" ] || [ -z "${environment}" ]; then
            echo "ERROR: Missing required parameters. Usage: atmos workflow plan-environment tenant=<tenant> account=<account> environment=<environment>"
            exit 1
          fi
          
          # Set stack name
          STACK="${tenant}-${account}-${environment}"
          
          # We'll auto-discover dependencies from imports and references
          
          # Discover available components by looking at stack files
          ENV_DIR="stacks/account/${account}/${environment}"
          echo "Discovering components in ${ENV_DIR}..."
          
          # Check if directory exists
          if [ ! -d "${ENV_DIR}" ]; then
            echo "ERROR: Environment directory ${ENV_DIR} does not exist."
            exit 1
          fi
          
          # Auto-discover component dependencies by analyzing YAML imports and output references
          echo "Auto-detecting component dependencies..."

          # Find all component configuration files
          AVAILABLE_COMPONENTS=()
          for file in ${ENV_DIR}/*.yaml; do
            if [ -f "$file" ]; then
              # Extract component name from filename (removing path and extension)
              component=$(basename "$file" .yaml)
              AVAILABLE_COMPONENTS+=("$component")
            fi
          done
          
          if [ ${#AVAILABLE_COMPONENTS[@]} -eq 0 ]; then
            echo "WARNING: No components found in ${ENV_DIR}"
            exit 0
          fi
          
          # Base dependency detection logic - analyze imports and outputs references
          # This builds a dependency graph automatically
          declare -A DEPENDENCIES
          
          # Function to extract imports from a YAML file
          extract_imports() {
            local file=$1
            local imports=()
            
            # Extract imports section if it exists
            if grep -q "^import:" "$file" || grep -q "^imports:" "$file"; then
              # Extract lines after import: until the next section
              imports=($(grep -A20 "^import:" "$file" | grep -v "^import:" | grep -v "^---" | grep -v "^$" | grep -v "^vars:" | sed 's/^\s*-\s*//' | sed 's/catalog\///' 2>/dev/null))
              if [ ${#imports[@]} -eq 0 ]; then
                imports=($(grep -A20 "^imports:" "$file" | grep -v "^imports:" | grep -v "^---" | grep -v "^$" | grep -v "^vars:" | sed 's/^\s*-\s*//' | sed 's/catalog\///' 2>/dev/null))
              fi
            fi
            
            echo "${imports[@]}"
          }
          
          # Function to detect output references
          detect_references() {
            local file=$1
            local references=()
            
            # Look for ${output.XXX} patterns which indicate dependencies
            if grep -q "\${output\." "$file"; then
              references=($(grep -o '\${output\.[^.]*' "$file" | sort | uniq | sed 's/\${output\.//' 2>/dev/null))
            fi
            
            echo "${references[@]}"
          }
          
          # Build dependency map for each component
          for component in "${AVAILABLE_COMPONENTS[@]}"; do
            DEPENDENCIES[$component]=""
            
            # Get the component's YAML file
            component_file="${ENV_DIR}/${component}.yaml"
            
            # Extract imports and references
            imports=($(extract_imports "$component_file"))
            references=($(detect_references "$component_file"))
            
            # Add all dependencies
            for dep in "${imports[@]}" "${references[@]}"; do
              # Skip non-component dependencies
              if [[ " ${AVAILABLE_COMPONENTS[*]} " =~ " ${dep} " ]]; then
                DEPENDENCIES[$component]="${DEPENDENCIES[$component]} $dep"
              fi
            done
            
            # Trim and remove duplicates
            DEPENDENCIES[$component]=$(echo "${DEPENDENCIES[$component]}" | tr ' ' '\n' | sort | uniq | tr '\n' ' ' | xargs)
          done
          
          # Topological sort function to order components based on dependencies
          topological_sort() {
            local -a visited=()
            local -a temp=()
            local -a order=()
            
            # DFS-based topological sort
            visit() {
              local node=$1
              
              # Check if already in result
              if [[ " ${order[*]} " =~ " ${node} " ]]; then
                return
              fi
              
              # Check for cycles
              if [[ " ${temp[*]} " =~ " ${node} " ]]; then
                echo "WARNING: Circular dependency detected involving $node"
                return
              fi
              
              # Mark as being visited
              temp+=("$node")
              
              # Visit dependencies first
              local deps=(${DEPENDENCIES[$node]})
              for dep in "${deps[@]}"; do
                visit "$dep"
              done
              
              # Add to result
              order+=("$node")
            }
            
            # Visit each node
            for component in "${AVAILABLE_COMPONENTS[@]}"; do
              visit "$component"
            done
            
            echo "${order[@]}"
          }
          
          # Generate ordered component list
          ORDERED_COMPONENTS=($(topological_sort))
          
          # Always ensure these core components come first if they exist
          CORE_COMPONENTS=("backend" "iam" "network")
          FINAL_ORDER=()
          
          # First add core components in the specified order
          for core in "${CORE_COMPONENTS[@]}"; do
            if [[ " ${AVAILABLE_COMPONENTS[*]} " =~ " ${core} " ]]; then
              if [[ ! " ${FINAL_ORDER[*]} " =~ " ${core} " ]]; then
                FINAL_ORDER+=("$core")
              fi
            fi
          done
          
          # Then add the rest from our sorted order
          for component in "${ORDERED_COMPONENTS[@]}"; do
            if [[ ! " ${FINAL_ORDER[*]} " =~ " ${component} " ]]; then
              FINAL_ORDER+=("$component")
            fi
          done
          
          # Log the automatically determined dependency order
          echo "Detected component order: ${FINAL_ORDER[*]}"
          
          # Use our final order
          ORDERED_COMPONENTS=("${FINAL_ORDER[@]}")
          
          echo "============================================"
          
          # Function to plan a component with error handling
          plan_component() {
            component=$1
            echo "Planning ${component}..."
            echo "----------------------------------------"
            
            if ! atmos terraform plan ${component} -s ${STACK}; then
              echo "WARNING: Plan failed for ${component}."
              # Continue with other components even if one fails
            fi
            echo "----------------------------------------"
          }
          
          # Plan components in dependency order first
          for component in "${ORDERED_COMPONENTS[@]}"; do
            # Check if this component exists in the available components list
            if [[ " ${AVAILABLE_COMPONENTS[*]} " =~ " ${component} " ]]; then
              plan_component "$component"
            fi
          done
          
          # Then plan any components that weren't in our known ordering
          for component in "${AVAILABLE_COMPONENTS[@]}"; do
            # Check if this component was already planned in the ordered phase
            if [[ ! " ${ORDERED_COMPONENTS[*]} " =~ " ${component} " ]]; then
              echo "Planning unordered component ${component}..."
              plan_component "$component"
            fi
          done
          
          echo "============================================"
          echo "Planning completed for ${STACK}"
