name: plan-environment
description: "Plan changes for all components in an environment"

workflows:
  plan:
    steps:
    - run:
        command: |
          # Use Python-based CLI to plan all components
          gaia workflow plan-environment \
            --tenant ${tenant} \
            --account ${account} \
            --environment ${environment} \
            --output-dir ${output_dir:-} \
            --parallel ${parallel:-false}
            
          # Exit with appropriate status code
          if [ $? -eq 0 ]; then
            echo "Planning completed successfully."
          else
            echo "Planning had issues with one or more components."
            exit 1
          fi
        env:
          AWS_SDK_LOAD_CONFIG: 1