# Security configuration for {{ env_name }} environment
components:
  terraform:
    acm:
      vars:
        enabled: true
        name: "{{ env_name }}-acm"
        domain_name: "{{ env_name }}.example.com"
        subject_alternative_names:
          - "*.{{ env_name }}.example.com"
        validation_method: "DNS"
        
    external-secrets:
      vars:
        enabled: true
        name: "{{ env_name }}-external-secrets"
        namespace:
          name: "external-secrets"
          create: true