# Alexandria Library Module Metadata
# Version: 1.0.0

module:
  id: "waf-advanced"
  name: "Advanced WAF"
  version: "1.0.0"
  maturity: "stable"

  # Classification
  category: "security/network-security"
  subcategory: "waf"
  tags:
    - waf
    - web-application-firewall
    - owasp
    - bot-control
    - rate-limiting
    - ddos
    - security
    - cloudfront
    - alb

  # Description
  description: "Production-grade WAF with OWASP Top 10, bot control, and rate limiting"
  long_description: |
    Enterprise-grade AWS WAF module with pre-configured rule sets for OWASP Top 10 protection,
    bot control, rate limiting, IP reputation lists, geo-blocking, and custom rule builder.
    Optimized for cost-effective rule ordering and comprehensive logging to S3/CloudWatch.
    Supports both CloudFront and Application Load Balancer deployments.

  # Complexity
  complexity: "advanced"
  setup_time_minutes: 15
  variable_count: 42

  # Cost
  cost:
    estimated_monthly_usd: 85
    cost_category: "medium"
    cost_factors:
      - "Web ACL: $5/month"
      - "Rules: $1/month per rule"
      - "Requests: $0.60 per 1M requests"
      - "Bot Control: $10/month + $1 per 1M requests"
      - "Logging: S3/CloudWatch storage costs"
    cost_breakdown:
      web_acl: 5
      managed_rules: 25
      custom_rules: 15
      bot_control: 20
      requests: 15
      logging: 5

  # Ownership
  maintainer:
    team: "Security Engineering"
    primary: "security-team@example.com"
    backup: "platform-team@example.com"

  # Support
  support:
    channel: "#security-support"
    sla: "12 hours"
    oncall: "security-oncall"

  # Dependencies
  dependencies:
    terraform_version: ">= 1.5.0"
    provider_versions:
      aws: ">= 5.0.0, < 6.0.0"
    required_modules: []

  # Compatibility
  compatible_with:
    - "cloudfront"
    - "alb"
    - "apigateway"
    - "monitoring"
    - "security-monitoring"

  incompatible_with: []
  replaces: []
  replaced_by: null

  # Metrics
  metrics:
    downloads: 0
    rating: 0.0
    rating_count: 0
    deployments: 0
    active_deployments: 0
    issues_open: 0
    issues_closed: 0
    last_updated: "2025-12-02"
    first_published: "2025-12-02"

  # Lifecycle
  lifecycle:
    created: "2025-12-02"
    stabilized: "2025-12-02"
    deprecated: null
    deprecation_reason: null
    removed: null
    replacement: null
    migration_guide: null

  # Documentation
  documentation:
    readme_url: "./README.md"
    changelog: "./CHANGELOG.md"
    architecture_diagram: "./docs/architecture.md"
    migration_guides: []
    examples:
      - path: "./examples/basic"
        description: "Basic WAF with OWASP Core Rule Set"
        complexity: "intermediate"
      - path: "./examples/advanced"
        description: "Advanced WAF with bot control and custom rules"
        complexity: "advanced"
      - path: "./examples/multi-region"
        description: "Multi-region WAF deployment"
        complexity: "advanced"

  # Testing
  testing:
    unit_tests: 18
    integration_tests: 8
    coverage_percent: 85
    last_test_run: "2025-12-02T10:00:00Z"
    test_status: "passing"
    test_duration_seconds: 240

  # Security
  security:
    checkov_passing: true
    tfsec_passing: true
    terrascan_passing: true
    last_scan: "2025-12-02"
    vulnerabilities:
      critical: 0
      high: 0
      medium: 0
      low: 0
    compliance:
      - "OWASP Top 10"
      - "CIS AWS Foundations"
      - "PCI DSS"
      - "HIPAA"

  # Performance
  performance:
    deployment_time_seconds: 900
    resource_count: 25
    state_size_kb: 120
