---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: vpc
  title: Virtual Private Cloud
  description: AWS VPC with public/private subnets, NAT gateways, and network security
  tags:
    - infrastructure
    - networking
    - aws
    - terraform
    - vpc
  annotations:
    backstage.io/source-location: 'dir:../../../../components/terraform/vpc'
    atmos.tools/component: 'vpc'
    atmos.tools/type: 'terraform'
    cost.platform.com/monthly-estimate: '$45-90'
    compliance.platform.com/framework: 'SOC2,ISO27001'
    backstage.io/techdocs-ref: 'dir:../../../../components/terraform/vpc'
    github.com/project-slug: 'your-org/infrastructure'
spec:
  type: infrastructure-service
  lifecycle: production
  owner: platform-team
  system: infrastructure
  dependsOn:
    - component:iam
  providesApis:
    - aws-vpc-api
  consumesApis:
    - aws-ec2-api
    - aws-route53-api

  # VPC-specific metadata
  vpc:
    cidrBlocks:
      - '10.0.0.0/16'  # Default for development
      - '10.1.0.0/16'  # Production networks
      - '10.2.0.0/16'  # Staging environments

    subnets:
      public:
        count: 3
        cidrSize: '/24'
      private:
        count: 3
        cidrSize: '/24'
      database:
        count: 3
        cidrSize: '/28'

    features:
      natGateway: true
      vpnGateway: false
      flowLogs: true
      dnsHostnames: true
      dnsSupport: true

---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: aws-vpc-api
  title: AWS VPC API
  description: AWS VPC service API endpoints and resources
spec:
  type: aws-service
  lifecycle: production
  owner: aws
  system: infrastructure
  definition: |
    # AWS VPC API endpoints provided by this component
    Resources:
      - VPC
      - Subnets (Public, Private, Database)
      - Route Tables
      - Internet Gateway
      - NAT Gateways
      - VPC Endpoints
      - Security Groups (default)
      - Network ACLs
      - VPC Flow Logs

    Outputs:
      - vpc_id
      - vpc_cidr_block
      - public_subnet_ids
      - private_subnet_ids
      - database_subnet_ids
      - nat_gateway_ips
      - vpc_endpoint_ids