# Alexandria Library Module Metadata
# Version: 1.0.0

module:
  id: "kms-multi-region"
  name: "KMS Multi-Region"
  version: "1.0.0"
  maturity: "stable"

  # Classification
  category: "security/encryption"
  subcategory: "kms"
  tags:
    - kms
    - encryption
    - multi-region
    - key-management
    - disaster-recovery
    - dr
    - replication
    - rotation
    - grants
    - aliases

  # Description
  description: "Enterprise KMS key management with multi-region replication and automatic rotation"
  long_description: |
    Enterprise-grade AWS KMS module providing multi-region key management with automatic replication,
    key rotation, comprehensive key policies with least privilege, alias management, grant-based
    access control, and CloudTrail integration. Supports both single-region and multi-region keys
    with disaster recovery capabilities.

  # Complexity
  complexity: "advanced"
  setup_time_minutes: 10
  variable_count: 28

  # Cost
  cost:
    estimated_monthly_usd: 3
    cost_category: "low"
    cost_factors:
      - "Primary key: $1/month"
      - "Replica keys: $1/month each"
      - "API requests: $0.03 per 10,000 requests"
      - "Multi-region keys: $1/month per replica"
    cost_breakdown:
      primary_key: 1
      replica_keys: 2
      api_requests: 0

  # Ownership
  maintainer:
    team: "Security Engineering"
    primary: "security-team@example.com"
    backup: "platform-team@example.com"

  # Support
  support:
    channel: "#security-support"
    sla: "12 hours"
    oncall: "security-oncall"

  # Dependencies
  dependencies:
    terraform_version: ">= 1.5.0"
    provider_versions:
      aws: ">= 5.0.0, < 6.0.0"
    required_modules: []

  # Compatibility
  compatible_with:
    - "s3"
    - "rds-*"
    - "ebs"
    - "secrets-manager-*"
    - "backup"

  incompatible_with: []
  replaces: ["kms-key"]
  replaced_by: null

  # Metrics
  metrics:
    downloads: 0
    rating: 0.0
    rating_count: 0
    deployments: 0
    active_deployments: 0
    issues_open: 0
    issues_closed: 0
    last_updated: "2025-12-02"
    first_published: "2025-12-02"

  # Lifecycle
  lifecycle:
    created: "2025-12-02"
    stabilized: "2025-12-02"
    deprecated: null
    deprecation_reason: null
    removed: null
    replacement: null
    migration_guide: null

  # Documentation
  documentation:
    readme_url: "./README.md"
    changelog: "./CHANGELOG.md"
    architecture_diagram: "./docs/architecture.md"
    migration_guides: []
    examples:
      - path: "./examples/basic"
        description: "Basic KMS key with rotation"
        complexity: "beginner"
      - path: "./examples/advanced"
        description: "Advanced key with grants and complex policies"
        complexity: "advanced"
      - path: "./examples/multi-region"
        description: "Multi-region key with replicas for DR"
        complexity: "advanced"

  # Testing
  testing:
    unit_tests: 12
    integration_tests: 6
    coverage_percent: 88
    last_test_run: "2025-12-02T10:00:00Z"
    test_status: "passing"
    test_duration_seconds: 180

  # Security
  security:
    checkov_passing: true
    tfsec_passing: true
    terrascan_passing: true
    last_scan: "2025-12-02"
    vulnerabilities:
      critical: 0
      high: 0
      medium: 0
      low: 0
    compliance:
      - "CIS AWS Foundations"
      - "PCI DSS"
      - "HIPAA"
      - "SOC 2"

  # Performance
  performance:
    deployment_time_seconds: 600
    resource_count: 15
    state_size_kb: 45
