import:
  - catalog/services

vars:
  account: dev
  environment: testenv-01
  region: eu-west-2
  tenant: fnx
  
dependencies:
  - eks
  - network

  # API Gateway specific overrides
  api_gateway.enabled: true
  api_gateway.name: "fnx-dev-testenv-01-api"
  api_gateway.description: "API Gateway for dev environment (testenv-01)"

  # Load Balancer specific overrides
  load_balancer.enabled: true
  load_balancer.name: "fnx-dev-testenv-01-alb"
  load_balancer.internal: false

  # CloudFront specific overrides
  cloudfront.enabled: false # Maybe disabled in dev

tags:
  Team: "DevOps"
  CostCenter: "IT"
  Project: "Infrastructure"